name: CD

# main branch로 병합이 되면 작동합니다
on:
  push:
    branches: [ main ]

env:
  # 이미지 이름을 환경변수로 등록합니다.
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/example-app

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      # Revision를 이미지의 태그로 만들기 위해 값을 생성합니다.
      - name: Get verion
        id: image
        run: |
          VERSION=$(echo ${{ github.sha }} | cut -c1-8)
          echo VERSION=$VERSION
          echo "::set-output name=version::$VERSION"
      # Container Registry에 로그인합니다.
      - name: Login to GitHub Packages Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # 애플리케이션을 이미지로 build 하고 push합니다.
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ steps.image.outputs.version }}
